version: '3.4'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27018:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db

    networks:
      - mongonetwork

  mysqldb:
    image: mysql:8.0
    volumes:
      - maboke-mysql-data:/var/lib/mysql
    networks:
      - mysqlnetwork
    ports:
      - "3308:3306"
    #env_file:
    #  - .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
      

volumes:
  maboke-mysql-data:

networks:
  mongonetwork:
    name: maboke_network
  mysqlnetwork:
    name: mysql_network  